# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=26.3-snapshot-1
	loader_version=0.19.3

# Mod Properties
	mod_version = 2.0.0-alpha.5+26.3-s1
	maven_group = me.yyna.transformhandlers
	archives_base_name = transformhandlers

# Dependencies
	fabric_version=0.153.1+26.3
	cloth_config_version=26.2.155
	mod_menu_version=20.0.0-beta.4
